### ISSUE TITLE
Make service instance states accessible

### ISSUE THREAD

**Issue by miklosduma** [sparkl/cli#42]
For automated tests, a utility to get complicated service instance state information would be useful.

Right now you can get this info running `sparkl show [InstanceID]`. 

This, however, does not return complicated service instance information. 

For example, if an Erlang map is kept in the service state, the above command will return `Map#{n}`, and you have no way to check what is actually kept in the map.

**Comment by jacobythwaites** [comment]
I don't think this is really feasible. Service state is internal and can be any term.

A service exposes its state through events (such as a reply event). That's our standard for getting service state.
