### ISSUE TITLE
Sparkl listen fails with username

### ISSUE THREAD

**Issue by miklosduma** [sparkl/cli#51]
If you enter `sparkl listen admin@sparkl.com` the generator does not pick up any events.

To listen to the root folder you either have to say:
- `sparkl listen /`
- `sparkl listen admin@sparkl.com/` - **NOTE** the `/` after the username

The `/` after the username should not be mandatory.

**Comment by jacobythwaites** [comment]
Actually I think this is correct behaviour. There are no events raised on the subject user at this time so nothing appears.
