### ISSUE TITLE
User registered through CLI cannot be deleted from UI

### ISSUE THREAD

**Issue by miklosduma** [sparkl/cli#9]
In CLI run:
```
sparkl connect [URL]
sparkl login -r [USER]
```

In Dev Console try deleting `[USER]`

**Comment by jacobythwaites** [comment]
This is an sse_core bug.

There is a separate but related sse_dc bug here:

 https://github.com/ethertricity/sse_dc/issues/62

**Comment by jacobythwaites** [comment]
This bug can no longer be reproduced.
